/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import filterapp.Main;

class AppTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        
    }
}
